Repository jaemisam-a/dangol-sonnim-backend, pull requests merged in 2023-02, with the labels that each got.

#5 [DS-32] QueryDsl 환경 설정
  build.gradle
  src/main/java/com/dangol/dangolsonnimbackend/config/QuerydslConfig.java
Labels: feat

#7 [DS-35] 사장님 Entity 추가
  src/main/java/com/dangol/dangolsonnimbackend/DangolSonnimBackendApplication.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/domain/Boss.java
  src/main/java/com/dangol/dangolsonnimbackend/config/JpaAuditingConfig.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/domain/BossTest.java
Labels: feat

#8 [DS-36] 사장님 Repository 추가
  src/main/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepository.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepositoryTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepositoryTest.java
Labels: feat

#14 [DS-48]사장님 Entity 와 Repository 관련 브랜치가 main 브랜치에 정상적으로 머지되지 않은 현상 해결
  src/main/java/com/dangol/dangolsonnimbackend/boss/domain/Boss.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepository.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
  src/main/java/com/dangol/dangolsonnimbackend/config/JpaAuditingConfig.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/domain/BossTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepositoryTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepositoryTest.java
Labels: bug

#16 [DS-39]사장님 회원가입 관련 Service 추가(재 업로드)
  src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/BossService.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
  src/main/java/com/dangol/dangolsonnimbackend/config/SecurityConfig.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepositoryTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepositoryTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImplTest.java
Labels: feat

#9 [DS-38]API Response 및 RestApiExceptionHandler 추가
  src/main/java/com/dangol/dangolsonnimbackend/errors/BadRequestException.java
  src/main/java/com/dangol/dangolsonnimbackend/errors/RestApiExceptionHandler.java
  src/main/java/com/dangol/dangolsonnimbackend/errors/enumeration/ErrorCodeMessage.java
Labels: feat

#18 DS-45 [가게] 엔티티 클래스 설계 및 정의
  src/main/java/com/dangol/dangolsonnimbackend/store/domain/Store.java
  src/main/java/com/dangol/dangolsonnimbackend/store/dto/StoreSignupRequestDTO.java
  src/test/java/com/dangol/dangolsonnimbackend/store/domain/StoreTest.java
Labels: feat

#15 DS-44 [CI/CD] 배포 환경에 따른 CI/CD 작업을 진행할 수 있도록 yml 파일 추가 정의
  .github/workflows/master-cicd.yml
  dockerfile
Labels: enhancement

#21 DS-42/43 [손님] Entity & DTO 구현
  src/main/java/com/dangol/dangolsonnimbackend/customer/domain/Customer.java
  src/main/java/com/dangol/dangolsonnimbackend/customer/domain/CustomerInfo.java
  src/main/java/com/dangol/dangolsonnimbackend/customer/dto/CustomerSignupRequestDTO.java
  src/test/java/com/dangol/dangolsonnimbackend/customer/domain/CustomerTest.java
Labels: feat

#17 [DS-40] 사장님 Controller 추가 & 회원 가입 Api 추가
  build.gradle
  src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/domain/Boss.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/dto/BossSignupRequestDTO.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/BossService.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
  src/main/java/com/dangol/dangolsonnimbackend/config/SecurityConfig.java
  src/main/java/com/dangol/dangolsonnimbackend/errors/enumeration/ErrorCodeMessage.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/domain/BossTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/repository/BossRepositoryTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepositoryTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImplTest.java
Labels: feat

#22 DS-45 [가게] 엔티티 클래스 설계 및 정의
  src/main/java/com/dangol/dangolsonnimbackend/store/domain/Store.java
  src/main/java/com/dangol/dangolsonnimbackend/store/dto/StoreSignupRequestDTO.java
  src/test/java/com/dangol/dangolsonnimbackend/store/domain/StoreTest.java
Labels: feat

#23 DS-49 [가게] Repository 클래스 설계 및 정의
  src/main/java/com/dangol/dangolsonnimbackend/store/repository/StoreRepository.java
  src/main/java/com/dangol/dangolsonnimbackend/store/repository/dsl/StoreQueryRepository.java
  src/test/java/com/dangol/dangolsonnimbackend/store/repository/StoreRepositoryTest.java
  src/test/java/com/dangol/dangolsonnimbackend/store/repository/dsl/StoreQueryRepositoryTest.java
Labels: feat

#24 DS-54 [이미지 테이블] Entity & DTO 구현
  src/main/java/com/dangol/dangolsonnimbackend/file/domain/FileAttachment.java
  src/main/java/com/dangol/dangolsonnimbackend/file/domain/FileBlob.java
  src/main/java/com/dangol/dangolsonnimbackend/file/dto/SaveFileDTO.java
  src/test/java/com/dangol/dangolsonnimbackend/file/domain/FileTest.java
Labels: feat

#28 DS-50 [사장님] 사장님 정보 조회하기 추가
  src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/dto/BossResponseDTO.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
Labels: feat

#30 DS-66 [사장님] 사장님 비밀번호 수정 API 추가
  src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/domain/Boss.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/dto/BossPasswordUpdateReqeuestDTO.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/BossService.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImplTest.java
Labels: feat

#32 DS-68 [사장님] 사장님 계정찾기 API 추가
  src/main/java/com/dangol/dangolsonnimbackend/boss/controller/BossController.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/dto/BossFindEmailReqeustDTO.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/dto/BossFindEmailResponseDTO.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepository.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/BossService.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImpl.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/controller/BossControllerTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/repository/dsl/BossQueryRepositoryTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/service/impl/BossServiceImplTest.java
Labels: feat

#36 DS-77 [기능구현] 어플리케이션 헬스 체크 추가
  build.gradle
Labels: feat

#31 DS-67 [사장님] 이메일 인증 API 추가
  .github/workflows/develop-ci.yml
  build.gradle
  src/main/java/com/dangol/dangolsonnimbackend/boss/controller/EmailController.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/dto/AuthCodeRequestDTO.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/dto/AuthCodeResponseDTO.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/EmailService.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/EmailServiceImpl.java
  src/main/java/com/dangol/dangolsonnimbackend/errors/enumeration/ErrorCodeMessage.java
  src/main/resources/templates/mail.html
  src/test/java/com/dangol/dangolsonnimbackend/boss/controller/EmailControllerTest.java
Labels: feat

#35 DS-70 [사장님] 이메일 인증 비동기 적용
  .github/workflows/master-cicd.yml
  build.gradle
  src/main/java/com/dangol/dangolsonnimbackend/boss/controller/EmailController.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/EmailService.java
  src/main/java/com/dangol/dangolsonnimbackend/boss/service/impl/EmailServiceImpl.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/controller/EmailControllerTest.java
  src/test/java/com/dangol/dangolsonnimbackend/boss/service/impl/EmailServiceImplTest.java
Labels: feat
